<a href="https://colab.research.google.com/github/ugurcancakal/network_pytorch/blob/master/basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Machine Learning**

rule and data -> classical programming -> answers

data and answers -> machine learning -> rules

# Tensors and Gradients

pytorch -> processing the tensors

tensor is a number, vector, matrix or any n-dimensional array

**WHAT MAKES PYTORCH SPECIAL?**

We can automatically compute the derivative of y with respect to the tensors that have requies_grad set to true. To compute the derivatives we can call the 
.backward method 

In [1]:
import torch

In [2]:
# Number
t1 = torch.tensor(4.)
print(t1)

tensor(4.)


In [3]:
t1.dtype 

torch.float32

In [4]:
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [5]:
t3 = torch.tensor([[5.,6.],[7,8],[9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [6]:
t4 = torch.tensor([
                   [[11,12,13],
                    [13,14,15]],
                   [[15,16,17],
                    [18,19,20]]])
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [18, 19, 20]]])

In [7]:
print(t1.shape)
print(t2.shape)
print(t3.shape)
print(t4.shape)

torch.Size([])
torch.Size([4])
torch.Size([3, 2])
torch.Size([2, 2, 3])


In [8]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(5., requires_grad = True)

In [9]:
y = w*x +b
print(y)

tensor(17., grad_fn=<AddBackward0>)


In [10]:
y.backward()


In [11]:
print('dy/dx: ', x.grad)
print('dy/dw ', w.grad)
print('dy/db ', b.grad)

dy/dx:  None
dy/dw  tensor(3.)
dy/db  tensor(1.)


# numpy, pandas, opencv

pytorch is optimized for GPU, however most of the preprocessing is made in numpy. Hopefully, torch has great interoperability with numpy

In [12]:
import numpy as np

x = np.array([[1,2], [3,4]])
z = torch.from_numpy(x) # shallow copy
y = torch.tensor(x) # deep copy
print(y)

tensor([[1, 2],
        [3, 4]])


In [13]:
t = y.numpy()
print(t)

[[1 2]
 [3 4]]
